Handle fpms freezing scenario when g_vars['option_selected']() returns a list instead of a func
Traceback (most recent call last):
  File "bakebit_nanohat_oled.py", line 664, in <module>
    g_vars['option_selected']()
TypeError: 'list' object is not callable